### ISSUE TITLE
Imports in main module

### ISSUE THREAD

**Issue by vreuter** [databio/refgenconf#16]
There are declared imports from `ubiquerg` that don't exist. Are these to be imported from elsewhere, moved to ubiquerg, or defined locally?

**Comment by vreuter** [comment]
https://github.com/databio/refgenie/commit/04604009fea007aff744734485ac7b5b97268226
https://github.com/databio/refgenie/commit/43e8c1e8cec8f8ac0052857ac72eca9a88a7a870

**Comment by vreuter** [comment]
@nsheff what's your thought re: placement of those functions? `query_yes_no` has definitely come up before, and `checksum` indeed seems sufficiently broadly applicable to warrant placement in `ubiquerg`.

**Comment by michalstolarczyk** [comment]
> Are these to be imported from elsewhere, moved to ubiquerg, or defined locally?

They are defined in `ubiquerg`, but on dev

I've decided to move them there since:

- `checksum` is used in both `refgenieserver` and in `refgenconf` (after the transfer of `pull_assets`)
- `query_yes_no` is used in both `looper` and `refgenconf` (after the transfer of `pull_assets`)

The `checksum` might leave just in `refgenconf`, but maybe it will be useful at some point in pepkit (?)

**Comment by nsheff** [comment]
I have no strong preference. I would probably put them all in ubiquerg.

**Comment by nsheff** [comment]
(assuming checksum doesn't introduce a dependency, right?)

**Comment by vreuter** [comment]
> (assuming checksum doesn't introduce a dependency, right?)

yeah just a standard library module (`hashlib`)
