### ISSUE TITLE
minimum version

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#26]
is the minimum version really 3.5? why?

https://github.com/databio/refgenconf/blob/eb45a8549024214f4f083e505f8e8599846e59b4/setup.py#L4

**Comment by vreuter** [comment]
Because during initial development discussion with you and @michalstolarczyk it was decided to only support Python 3 for the `refgenie` suite of packages (this, server, and conf). 3.4 is considered "end of life," so minimum bound of 3.5 seems reasonable; this formalizes it so we don't have users installing on platforms that we have no desire to support.

**Comment by vreuter** [comment]
https://www.python.org/downloads/release/python-340/

**Comment by nsheff** [comment]
I was just curious if it actually didn't work on python 2.

The thing is, this will make pepatac for example also require python 3 since it will import refgenconf (but we still don't even have a version released that works in python 3), making this a little complicated...
