### ISSUE TITLE
imprecise message when pulling non-existent asset/genome pair

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenconf#39]
the response is correct (see code example in: https://github.com/databio/refgenie/pull/28#discussion_r293025543), as there's no `bowtie2_index` asset for `hg38` genome (and it's true for all genomes), try: http://refgenomes.databio.org/asset/hg38/bowtie2_index/archive

however now the error/message that we get is not precise, and I think it's caused by the introduction of the [connection pre-check](https://github.com/databio/refgenconf/issues/32) that we do for `refgenie pull`

_Originally posted by @michalstolarczyk in https://github.com/databio/refgenie/pull/28/review_comment/create_

**Comment by vreuter** [comment]
What do you want the message to be?

**Comment by michalstolarczyk** [comment]
sth like: " '{bundle_name}' not found on the server"?

**Comment by vreuter** [comment]
Well `_download_json` only gets the URL, so given the current signature it doesn't know what's trying to be accessed. I could make `DownloadJsonError` wrap a reference to the actual `Response` object from `requests.get`, though, so that the `refgenconf` dependent like `refgenie` or `refgenieserver` could make use of the JSON data that it contains (`r.json()`, where `r` is the `Response` instance).

**Comment by vreuter** [comment]
```
In [8]: r.json()                                                                                                                                                                                            
Out[8]: {'detail': 'No such asset on server'}
```
So then the client code can decide how it wants to recover from or render the exception.

**Comment by michalstolarczyk** [comment]
this sounds like a robust solution

but do you mean it will introduce a _package_ dependency on `refgenieserver`?

**Comment by vreuter** [comment]
No, sorry for ambiguity. I mean that I'm deliberately not going to use the knowledge of the JSON that `refgenieserver` places in the response via the `MSG_404` formatting, so that `refgenconf` remains "unaware" both literally and conceptually of `refgenieserver`. Instead, I'll give access to the fuller response data so that `refgenie` and/or `refgenieserver` (or any other package that comes to use `refgenconf`) can handle it as desired, rather than compressing some of that information as is done now, since `refgenconf` just injects a simplified error message.

**Comment by michalstolarczyk** [comment]
That’s great
