### ISSUE TITLE
sort results of `list` and `listr`

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#41]
sort results of `list` and `listr`

Raised by @afrenderio

**Comment by nsheff** [comment]
another thought: 

then maybe assets should be sorted within genomes.

I guess it *is* more complicated than I was thinking :)

**Comment by vreuter** [comment]
I think the lack of an immediately obvious sort actually changes my initial suggestion--I think this should be handled in `refgenie` itself. Parameterize-with-default would make more sense if there was an clear default, but it seems like taste may differ among users/applications that would make calls to those functions.

This feels more like a question for a "rendering' layer question than an "information provision" layer, so I think handling it in `refgenie` rather than here also more closely aligns implementation with conceptual intuition.

**Comment by vreuter** [comment]
Yeah I'll provide directly in this package (propagating to `refgenie`) ordering parameters with the default behavior that @nsheff  describes. Delegating sorts to client code would require one of several unfavorable changes (significant API expansion, loss of information hiding, or reparsing returned text), so I think introducing it here is the least of several evils.

**Comment by nsheff** [comment]
what about local assets though? should those be sorted as well?

**Comment by vreuter** [comment]
Yes. the implementation will aim to treat them equivalently.

**Comment by nsheff** [comment]
that's fine I guess. local assets just seem less clear to me because it seems more reasonable to just order them in the way the person has sorted them in the config file...

but in the end I think you're right. let's just have them always sorted at display. I think that's what basically all users will want basically all the time.

**Comment by vreuter** [comment]
Yeah I prefer to standardize the order by default since many of the updates to a local config may be automatic via the update functionality
